name: "build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: G11n Analysis
        uses: ./ # Uses an action in the root directory
        with:
          languages: en-US fr-FR
      - name: Actifacts publish
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: g11n-result
          path: detail.csv
